### PR TITLE
Add date-filter prefix to prevent clashes. Fixes #7

### LINKED ISSUE #7: Broken
Throws JS error on selecting input

### PR DESCRIPTION
**Pull request by niladam**
The issue #7 was actually related to the fact that i already had a different component that used flatpickr (not a filter component though).

What i did was, i've added a class so that i can style accordingly. The classes get added `onReady` and the style changes now reflect that.

Should fix the issue i've been having as well as future issues where people might stumble onto the same situation.

### CODE REVIEW

**Comment by disitec** [comment]
Reselased `0.3.1` 🎉 

Thank you!

**Comment by niladam** [comment]
You're welcome. Also, can you make sure you update the novapackages listing as well ?

**Comment by niladam** [comment]
Btw, i'm registered there as well -- so you can 'claim' me as a collaborator :)

**Comment by disitec** [comment]
I think you have to go to novapackages and claim to collaborator. Then I could accept you

**Comment by disitec** [comment]
I found it! You are in now!

**Pull request merged**
