### PR TITLE
leave room for more custom filters

### PR DESCRIPTION
**Pull request by avrahamappel**
In order to be able to have more custom filter components (I will add a searchable one using `vue-select` next), I changed the hardcoded DatePicker component into a dynamic component which will accept any component name we give it from the backend. I then registered the DatePicker component globally, and passed the name into the `filter` object to be used in the dynamic component.

### CODE REVIEW

**Comment by disitec** [comment]
Hey, Thank you for this PR. Looks awesome.

Can you give me an example of how can I change the component from backend? I cant see any way except redeclaring jsonSerialize.

And one more thing. Can you back to two spaces in templates and respect this rule https://vuejs.org/v2/style-guide/#Multi-attribute-elements-strongly-recommended

There are a lot of diffs that are simply style differences. We want to stick to the recommended

Thank you!

**Comment by avrahamappel** [comment]
@disitec I'm not sure what you have in mind, but the idea is that you add to the `jsonSerialize` array:
```php
'customComponent' => true, // so it will use the dynamic component instead of the native select
'component'       => 'name-of-your-custom-component-here',
``` 
So whatever Vue component you have registered by that name will be rendered, and the full `filter` object will be passed to it, as well as a `value` which is the initial filter value. Then make sure it emits an `input` event when changed, and we're good to go. 

I guess we could have a base `CustomFilter` class or something:
```php
use Laravel\Nova\Filters\Filter;
	
abstract class CustomFilter extends Filter
{	
    public function jsonSerialize()
    {
        return array_merge(parent::jsonSerialize(), [
            'customComponent' => true,
            'component'       => $this->componentName(),
        ])
    }

    /**
     * @return  string
     */
    protected abstract function componentName();
}
```
And then all we have to do is
```php
abstract class DateFilter extends CustomFilter
{
    protected function componentName()
    {
        return 'date-filter';
    }
}
```

**Comment by avrahamappel** [comment]
And sorry about the code style, I'll try to fix that (although it seems that the Laravel team isn't overly concerned about it either, I just copied the code from the original and that's how it came)

**Comment by disitec** [comment]
Thans for your work @avrahamappel . I would go with that componentName method. What about making it a normal method with a default vaule of `date-filter` and allow user to redeclare it in case they want a different one?

**Comment by avrahamappel** [comment]
*Oops, I meant `date-picker`, not `date-filter` 😆

**Comment by disitec** [comment]
Thank you. This feature looks pretty awesome!

**Comment by disitec** [comment]
Available in 0.2.0 🎉

**Pull request merged**
